sudo: false
language: ruby
cache: bundler

before_script:
  - psql -c 'create database rails_state_machine_test;' -U postgres
  - mysql -e 'create database IF NOT EXISTS rails_state_machine_test;'

install:
  # Replace default Travis CI bundler script with a version that doesn't
  # explode when lockfile doesn't match recently bumped version
  - bundle install --no-deployment --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

script: bundle exec rake current_rspec

matrix:
  include:
    - rvm: 2.3.8
      gemfile: Gemfile.5.1.pg
    - rvm: 2.4.6
      gemfile: Gemfile.5.1.pg
    - rvm: 2.3.8
      gemfile: Gemfile.5.2.pg
    - rvm: 2.4.6
      gemfile: Gemfile.5.2.pg
    - rvm: 2.5.6
      gemfile: Gemfile.5.2.pg
    - rvm: 2.5.6
      gemfile: Gemfile.6.0.pg
    - rvm: 2.6.4
      gemfile: Gemfile.6.0.pg

dist: trusty
